language: go
go:
  - 1.2

before_script:
  - go get -u github.com/mattn/goveralls
  - go get -u code.google.com/p/go.tools/cmd/cover

install:
  - go get -u github.com/onsi/gomega
  - go get -u github.com/onsi/ginkgo

script:
  - go build
  - go test -v ./...
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci